# Generated by Django 4.0.4 on 2024-08-24 12:30

from django.db import migrations
import ecommerce.inventory.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_product_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=ecommerce.inventory.fields.OrderField(default=None),
            preserve_default=False,
        ),
    ]
