# Generated by Django 4.0.4 on 2024-08-24 19:34

from django.db import migrations
import ecommerce.inventory.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=ecommerce.inventory.fields.HexColorField(blank=True, max_length=6, null=True),
        ),
    ]
