# Generated by Django 4.0.4 on 2024-08-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
